//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nashotelru.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nashotelru.Resources.Shared.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVERVIEW.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVITIES.
        /// </summary>
        public static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50, 11-ya Liniya, Vasilievsky Ostrov, St Petersburg.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adults.
        /// </summary>
        public static string BK_Adults {
            get {
                return ResourceManager.GetString("BK_Adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check in.
        /// </summary>
        public static string BK_CheckIn {
            get {
                return ResourceManager.GetString("BK_CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out.
        /// </summary>
        public static string BK_CheckOut {
            get {
                return ResourceManager.GetString("BK_CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        public static string BK_Children {
            get {
                return ResourceManager.GetString("BK_Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string BK_Find {
            get {
                return ResourceManager.GetString("BK_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promocode.
        /// </summary>
        public static string BK_Promocode {
            get {
                return ResourceManager.GetString("BK_Promocode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        public static string BK_Rooms {
            get {
                return ResourceManager.GetString("BK_Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOKING.
        /// </summary>
        public static string Booking {
            get {
                return ResourceManager.GetString("Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACTS.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string DM_Activities {
            get {
                return ResourceManager.GetString("DM_Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking.
        /// </summary>
        public static string DM_Booking {
            get {
                return ResourceManager.GetString("DM_Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridges.
        /// </summary>
        public static string DM_Bridges {
            get {
                return ResourceManager.GetString("DM_Bridges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string DM_Contacts {
            get {
                return ResourceManager.GetString("DM_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVENTS.
        /// </summary>
        public static string DM_Events {
            get {
                return ResourceManager.GetString("DM_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOTEL.
        /// </summary>
        public static string DM_Hotel {
            get {
                return ResourceManager.GetString("DM_Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string DM_Information {
            get {
                return ResourceManager.GetString("DM_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string DM_News {
            get {
                return ResourceManager.GetString("DM_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responses.
        /// </summary>
        public static string DM_Responses {
            get {
                return ResourceManager.GetString("DM_Responses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        public static string DM_Restaurant {
            get {
                return ResourceManager.GetString("DM_Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        public static string DM_Rooms {
            get {
                return ResourceManager.GetString("DM_Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVICES.
        /// </summary>
        public static string DM_Services {
            get {
                return ResourceManager.GetString("DM_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialOffers.
        /// </summary>
        public static string DM_SpecialOffers {
            get {
                return ResourceManager.GetString("DM_SpecialOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order of transfer.
        /// </summary>
        public static string DM_Transfer {
            get {
                return ResourceManager.GetString("DM_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career.
        /// </summary>
        public static string DM_Vacances {
            get {
                return ResourceManager.GetString("DM_Vacances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visas.
        /// </summary>
        public static string DM_Visas {
            get {
                return ResourceManager.GetString("DM_Visas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAX.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string HomeIndexTitle {
            get {
                return ResourceManager.GetString("HomeIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel NashOTEL.
        /// </summary>
        public static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGOFF.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWS.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR ROOMS.
        /// </summary>
        public static string OurRooms {
            get {
                return ResourceManager.GetString("OurRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHONE.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGNUP.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESTAURANT.
        /// </summary>
        public static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPECIAL OFFERS.
        /// </summary>
        public static string SpecialOffers {
            get {
                return ResourceManager.GetString("SpecialOffers", resourceCulture);
            }
        }
    }
}
