// <auto-generated />
namespace Nashotelru.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class dt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dt));
        
        string IMigrationMetadata.Id
        {
            get { return "201402161815241_dt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
